# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://exspeed.github.io/9_element_tattoo/'
baseurl: '/9_element_tattoo'
title: '9 Element'
description: 'This is my new website'
permalink: pretty
logo: "/assets/logos/Stroke-on-Trans-icon.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Tattoos: /tattoos
  News & Events: /events
  Store: /blog
  FAQS: /about

# Footer nav
navigation_footer:
  Back to top: "#top"

#Instagram
instagram:
  Jim Tran: 
    ig_handle:
      - jimtran_
      - jimtran_ll
    tags:
      Anime: animeink
      Traditional Japanese: asian_tattoo_
      Flowers: flowertattoo



# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
